name: .NET API

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_PATH: ./TappApi.csproj
  PUBLISH_DIR: publish
  SERVICE_NAME: maybe
  SERVER_APP_PATH: /var/www/maybe/publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - run: dotnet restore $PROJECT_PATH
    - run: dotnet build $PROJECT_PATH -c Release --no-restore
    - run: dotnet publish $PROJECT_PATH -c Release -o $PUBLISH_DIR

    - name: Upload to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "${{ env.PUBLISH_DIR }}/*"
        target: ${{ env.SERVER_APP_PATH }}
        strip_components: 1

    - name: Restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          systemctl daemon-reload
          systemctl restart maybe
          systemctl status maybe --no-pager -l
